### ISSUE TITLE
PCI compliance

### ISSUE THREAD

**Issue by erangac** [tranxactive/J2PAY#16]
Hi,
What level of PCI compliance expected to use this API ? I can see authorize API expecting credit card number ...etc.
Thanks

**Comment by ilyas2016** [comment]
Pci compliant is required when we store credit card. we are just providing library whoever 'll use it on his own domain or server which is saving customer card will required to be pci certified.

**Comment by ilyas2016** [comment]
Yes you are right.
If someone using this library they can certified there system.
But mostly the issue is raised when someone storing card detail then pci is must.
