### ISSUE TITLE
Paypal & Stripe Support

### ISSUE THREAD

**Issue by seedarren** [tranxactive/J2PAY#19]
Support for Stripe and Paypal Payments

**Comment by tranxactive** [comment]
Hey. We will try our best to integrate.

**Comment by tranxactive** [comment]
hey @seedarren,
It my pleasure to inform you that strip is now supported by J2pay version 2.8.8.

**Comment by seedarren** [comment]
Thanks

Sent from Yahoo Mail on Android 
 
  On Thu, Jan 3, 2019 at 3:58 PM, Tranxactive<notifications@github.com> wrote:   
hey @seedarren,
It my pleasure to inform you that strip is now supported by J2pay version 2.8.8.

**Comment by tranxactive** [comment]
dear @seedarren,
According to our understanding paypal required to redirect on paypal website, while we are only focused on server to server communication and for this paypal provide payflow pro that is already integrated in our library.
waiting for your response. I have to close this issue.

**Comment by seedarren** [comment]
Thanks for your effort. I have verified it. Really appreciate your effort

Sent from Yahoo Mail on Android 
 
  On Fri, Jan 4, 2019 at 5:04 PM, Tranxactive<notifications@github.com> wrote:   
dear @seedarren,
According to our understanding paypal required to redirect on paypal website, while we are only focused on server to server communication and for this paypal provide payflow pro that is already integrated in our library.
waiting for your response. I have to close this issue.
