### ISSUE TITLE
Redirect payment support

### ISSUE THREAD

**Issue by dearwish** [tranxactive/J2PAY#22]
Hi there,

I am looking for similar abstraction layer above different payment gateways. We already did several integrations with payment gateways, but they are all redirect based. This method consists of 2 steps:

1. We redirect our user to payment gateway webpage where he will enter his credit card details.
2. Once he done, the payment gateway calls a return page that is mapped to our REST API with payment status and payment token (partial credit card and customer details).

So I am trying to understand whether the J2pay payment flow has the redirect payment method support.

Thank you

**Comment by tranxactive** [comment]
Hey,
Thanks for reaching out.
J2pay does not support redirection methods.
It is designed to only worked on server side.

But we are interested to expand our library.
If you could help us with the redirection integrations i believe we can do that.

Thanks

**Comment by tousifhasanzai** [comment]
No j2pay doesn't support redirect payment method.
You will have to get card details at your own page and then your system
will call j2pay with reference to the gateway on which you want to process
payment.
J2pay will respond to you about payment confirmation.
In this way customer will always remains at your own website.
Hope this helps
