### ISSUE TITLE
Stored credit card/customer profiles

### ISSUE THREAD

**Issue by codelady7** [tranxactive/J2PAY#24]
Hello J2Pay team -

Do you have plans to support doing transactions using a stored customer profile? For example, Authorize.net lets you upload customer credit card information for secure storage on their servers, then you can reference the customer's profileID (Charge a Customer Profile) when creating a auth/capture transaction. PayPal uses Data Upload or Reference transactions where you use the refID in subsequent sale transactions.

My resellers tell me this is important for a fully functional credit card interface. Not only is it a convenience for the purchasing customer (not having to supply their card number with each sale), but it improves accuracy and PCI compliance since the ERP user doesn't have to continually ask for and record the number.

(Note: I tried emailing info@traxactive.com and it bounced with "address not found.")

**Comment by tranxactive** [comment]
Hey,
Sorry for inconvenient.
YES!! we are already have support for that.
You are taking about recurring/rebill. When you execute purchase or capture transaction J2pay automatically do that for you. and provide you the rebill parameters in library response (lr) to charge next time. you can see our documentation on  [http://j2pay.tranxactive.com](url).

If your business is dependent on recurring then it is highly recommended for you to please check if recurring supported on that gateway.

You can check that on our github home page.

Regards

**Comment by codelady7** [comment]
Sorry - I don't believe we are talking about the same thing. I am not talking about rebilling a prior purchase, or making a recurring purchase (such as a magazine subscription). I am talking about storing the customer credit card info with the gateway, so new purchases can be made without supplying the credit card info. I don't know if all of your supported gateways have this feature, but Authorize.net and PayFlow do.

Here is the URL for the PayFlow page that discusses Reference Transactions and Data Upload:
https://developer.paypal.com/docs/classic/payflow/integration-guide/?mark=Data%20Upload#submitting-reference-transactions---tokenization

Here is the Authorize.net page that shows how to do a purchase using a stored customer profile:
https://developer.authorize.net/api/reference/index.html#payment-transactions-charge-a-customer-profile

I'm not asking for J2Pay to provide the API for uploading/creating the customer profiles, but it would be great if we could do a purchase transaction and reference a stored profile.

Thanks.

**Comment by tranxactive** [comment]
Hey,
lets discus about Authorize.net 
If you are talking about creating customer profile before executing Auth/purchase transaction, then it is not supported by J2pay.
But there is another way to doing that in j2pay. which is you can execute the purchase/Auth transaction and j2pay will internally pass same extra parameters to authorize gateway so authorize.net will do two things in one request, first it will create the customer profile and then it will charge the transactions.
then J2pay will return you the rebill parameters containing the customer profile id that you could use to re-charge next time without passing customer card.

Hope that help you.
Please feel free to ask again if you have sill some concerns.

**Comment by codelady7** [comment]
Sorry, but no, I am *not* talking about rebilling or recurring. The rebill transaction is for rebilling a previously submitted charge, and recurring is for things such as subscriptions that you'd bill periodically (say once a month). What I am talking about (in terms of Authorize.net) is using their API to create a Customer Profile. I would not need J2Pay to do that. Then, any time the customer makes a *new* purchase, I can submit that transaction and use the ID for the customer profile, *instead* of sending the credit card number, expiration date, etc. I am asking if J2Pay has plans to support the ability to charge a customer profile, as referenced in the link I gave previously. Again, this is not the same as rebilling.

**Comment by tranxactive** [comment]
If you already have customer profile id,
you can use J2pay rebill method and pass the customer profile id in it.

**Comment by codelady7** [comment]
OK - I'll try it and see.
